# Generated by Django 4.2.8 on 2023-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contactNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
