# Generated by Django 4.2.8 on 2023-12-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_document_contactnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='User',
        ),
    ]
