# Generated by Django 4.2.8 on 2023-12-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contactNumber',
            new_name='contact',
        ),
    ]
